import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
print("--- Statistical Validation ---")
real_df = pd.read_csv("clean_medical_data.csv")
synth_df = pd.read_csv("synthetic_medical_data.csv")
real_corr = real_df.corr()
synth_corr = synth_df.corr()
fig, axes = plt.subplots(1, 2, figsize = (14, 5))
axes[0].set_title("Real Data Correlation ")
sns.heatmap(synth_corr, annot = True, cmap = "coolwarm", fmt = ".2f", ax = axes[1])
axes[1].set_title("Synthetic Data Correlation")
plt.tight_layout()
plt.savefig("correlation_comparison.png")
print("Korrelationssammenligning gemt som 'correlation_comparison.png")
plt.figure(figsize=(8, 4))
sns.kdeplot(real_df['age'], label = 'Real Data', color = 'blue', shade = True)
sns.kdeplot(synth_df['age'], label = 'Synthetic Data', color = 'orange', shade = True)
plt.title("Age Distribution Comparison")
plt.legend()
plt.tight_layout()
plt.savefig("age_distibution.png")
print("Alderfordeling gemt som 'age_distribution.png")
plt.show()